CREATE DATABASE IF NOT EXISTS telefoot;

USE telefoot;

CREATE TABLE users (
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE password_reset (
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL,
    token VARCHAR(100) NOT NULL
);

CREATE TABLE firstleague(
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    image VARCHAR(255) NOT NULL
);

CREATE TABLE channels(
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    image VARCHAR(255) NOT NULL
)